---
title: "Length of Stay Cox Regression Analysis"
output: html_notebook
---

```{r}
library(survival)
library(tidyverse)
library(ggfortify)
```

```{r}
#surv_data <- readRDS(file = "../data/ed_ex.rds")
#surv_data <- readRDS(file = "../../cw-data/cw_ip_spells.rds")
#surv_data <- readRDS(file = "../../lgt-data/data-out/spell_table_lgt_20190816_b704e260_ms.rds")
surv_data <- readRDS(file = "../../cw-data/spell_table_cw_20190902_b7fae6f7.rds")

spec_dir_mapping <- readr::read_csv("../data/SPECIALTY_HCPmap.csv")
surv_data <- surv_data %>% dplyr::left_join(spec_dir_mapping, by = c("main_specialty_start" = "spec_name"))

surv_data <- surv_data %>% filter(admission_method_type == "Emergency Admissions",
                                  !(age_band_start %in% c("1-4 yrs", "5-9 yrs", "10-14 yrs")),
                                  directorate == "Medical"#,
                                  #main_specialty_start %in% c("ACUTE INTERNAL MEDICINE", "GENERAL MEDICINE")
                                  ) %>%
  mutate(start_datetime = if_else(is.na(initial_ed_end_datetime), spell_start, initial_ed_end_datetime),
         end_datetime = spell_end,
         age_band_start = forcats::fct_drop(age_band_start))
surv_data <- surv_data %>% mutate(los = difftime(end_datetime, start_datetime), adm_wd = weekdays(start_datetime)) %>% filter(!is.na(los)) %>%
  mutate(days_since_prev_disch = as.numeric(replace(days_since_prev_disch, days_since_prev_disch <= 0, NA)),
         disch_in_last_week = if_else(!is.na(days_since_prev_disch) & days_since_prev_disch <=7, TRUE, FALSE),
         disch_in_last_month = if_else(!is.na(days_since_prev_disch) & days_since_prev_disch <=30, TRUE, FALSE),
         admitted_before = !is.na(days_since_prev_disch))
units(surv_data$los) <- "hours"
clean_surv_data <- surv_data %>% filter(!is.na(los) & los >= 0 & end_datetime < lubridate::ymd_hm('2019-03-01 00:00'))


obsLen <- 365*24 # length of observation time (censoring time = end of study)
clean_surv_data <- clean_surv_data %>% mutate(eventT = los,
                                              obsT = pmin(eventT, obsLen),
                                              status = eventT <= obsLen,
                                              gender = dplyr::if_else(gender == "Male", 1, 0),
                                              adm_calmonth = as.factor(format(start_datetime, "%b")),
                                              adm_daytime = dplyr::if_else(dplyr::between(lubridate::hour(start_datetime), 8, 16), 1, 0))
# eventT <- clean_surv_data %>% pull(los)
# adm_wd <- clean_surv_data %>% pull(adm_wd)
# obsT   <- pmin(eventT, obsLen)  # observed censored event times
# status <- eventT <= obsLen     # has event occured?

dfSurv <- clean_surv_data %>% select(eventT, obsT, status)
dfSurv2 <- clean_surv_data %>% select(spell_number, eventT, obsT, status,
                                      adm_wd, adm_calmonth, gender, age_band_start,
                                      start_datetime, end_datetime, adm_daytime, days_since_prev_disch, disch_in_last_week, disch_in_last_month, admitted_before)
```

