
#' recode_factors
#'
#' @param provided_data a tibble containing the imported dataset included all standard columns parsed
#' as the correct type
#' @param config_path path to the directory containing the config files for this dataset
#'
#' @return copy of provided_data with factor variables recoded to standard levels as
#' per the config files
#' @export
#'
#' @examples
recode_factors <- function(provided_data, config_path) {
  # TO BE IMPLEMENTED!

}


#' get_import_col_types
#'
#' @param config_path path to the config files for a given dataset
#'
#' @return a column specification to be used for parsing the dataset, as a named vector of
#' expressions. The expressions are readr collectors, and the names specify the columns they
#' will parse.
#' @export
#'
#' @examples
get_import_col_types <- function(config_path) {

  # Read in the mapping from provided column names to standard column names...
  column_mapping <- readRDS(file.path(config_path, "column_mapping.rds"))

  # get list of config files
  config_file_list <- Sys.glob(paste0(config_path, "*.rds"))

  # add column for file names of factor level config files in the config path
  column_mapping <- column_mapping %>% mutate(config_file_name = paste0(config_path, standard, "_levels.rds"),
                            factor_config_file = if_else(config_file_name %in% config_file_list, config_file_name, NA_character_)) %>%
    select(-config_file_name)

  get_provided_levels <- function(fn) {
    if(is.na(fn)) {
      return(NA)
    } else {
      readRDS(fn) %>% dplyr::pull(provided)
    }
  }

  gplv <- Vectorize(get_provided_levels)

  column_mapping <- column_mapping %>% mutate(provided_levels = gplv(factor_config_file))

  # Set up datetime formats
  datetime_formats <- readRDS(file.path(config_path, "datetime_formats.rds"))
  column_mapping <- column_mapping %>% left_join(datetime_formats, by = c("provided" = "column_name"))

  # Convert the vectors of provided factor levels to readr::col_factor expressions
  make_factor_import_spec <- function(...) {
    standard_col_name <- list(...)[["standard"]]
    provided_levels <- list(...)[["provided_levels"]]

    if(all(is.na(provided_levels))) return(NA)

    rlang::expr(readr::col_factor(levels = !!provided_levels))
  }

  column_mapping <- column_mapping %>% dplyr::mutate(importType = purrr::pmap(., function(...) make_factor_import_spec(...)))

  # Convert datetime formats to readr::col_datetime expressions
  make_datetime_import_spec <- function(...) {
    standard_col_name <- list(...)[["standard"]]
    datetime_format <- list(...)[["datetime_format"]]

    if(is.na(datetime_format)) return(NA)

    rlang::expr(readr::col_datetime(format = !!datetime_format))
  }

  column_mapping <- column_mapping %>% dplyr::mutate(importType = dplyr::if_else(is.na(importType),
                                                                                 purrr::pmap(., function(...) make_datetime_import_spec(...)),
                                                                                 importType))

  # Any remaining columns specified as readr::character expressions

  make_char_import_spec <- function(...) {
    rlang::expr(readr::col_character())
  }

  column_mapping <- column_mapping %>% dplyr::mutate(importType = ifelse(is.na(importType),
                                                                         purrr::pmap(., function(...) make_char_import_spec(...)),
                                                                                 importType))


  # Label the types with the respective column names and return this as a named
  # vector
  colImportTypes <- column_mapping %>% pull(importType)
  colImportNames <- column_mapping %>% pull(provided)
  colImportTypes <- rlang::set_names(colImportTypes, colImportNames)
  colImportTypes
}


#' get_colname_mapping
#'
#' @param config_path path to the config files for a given dataset
#'
#' @return character vector specifying column renaming, of the form
#' c(new_name_1 = "old_name_1", new_name_2 = "old_name_2")
#' @export
#'
#' @examples
get_colname_mapping <- function(config_path) {
  # Read in the mapping from provided column names to standard column names...
  column_mapping <- readRDS(file.path(config_path, "column_mapping.rds"))

  column_mapping
}

#' import_and_standardise
#'
#' @param data_import_list list of named lists, each named list has two elements called
#' data_path and config_path, whose values are character strings specifying the paths
#' to i) a csv file to import data from and ii) a folder containing hospitalflow config
#' files.
#'
#' @return list of tibbles, each containing standardised import of one data file from data_paths
#' @export
#'
#' @examples
import_and_standardise <- function(data_import_list) {

  # Take the data_import_list and for each element x, load the data located at data_path
  # using configuration specified by the files at config_path.
  # In particular, use the column specification generated by
  # get_import_col_types from the config files.
  data_config_list <- lapply(data_import_list,
                             function(x) {list(data = readr::read_csv(x$data_path,
                                                                      locale = readr::locale(tz = 'Europe/London'),
                                                                      col_types = eval(rlang::call2(readr::cols,
                                                                                                    !!!get_import_col_types(x$config_path),
                                                                                                    .default = readr::col_skip()))),
                                               config_path = x$config_path)
    })

  # Rename the columns in each imported dataset, using the name mapping onto standard hospitalflow
  # variable names specified in the config files at the specified config_path.
  data_config_list <- lapply(data_config_list,
                             function(x) {
                               list(data = standardise_column_names(x$data,
                                                                    get_colname_mapping(x$config_path) %>%
                                                                      dplyr::filter(provided %in% colnames(x$data))
                                                                    ),
                                    config_path = x$config_path)
                               })

  # HERE NEED TO DEAL WITH FORMAT CONVERSIONS: DATETIMES, FACTORS, ETC.

  # Extract the data as a tibble for each imported file, and return as a list of these tibbles.
  lapply(data_config_list, function(x) x$data)
}


# example_data_import_list <- list(list(data_path = "../lgt-data/data-extract-201901/CLAHRCExtractToSend_QEH_20190107_ED.csv",
#                                       config_path = "lgt-config/ed/"),
#                                  list(data_path = "../lgt-data/data-extract-201901/CLAHRCExtractToSend_UHL_20190104_ED.csv",config_path = "lgt-config/ed/"))
#
# cw_data_import_list <- list(list(data_path = "../cw-data/cw_ae_anonim.csv", config_path = "../cw_config_files/ed/"))
#
# cw_data_import_list_inpatient <- list(list(data_path = "../cw-data/cw_ip_anonim.csv", config_path = "../cw_config_files/inpatient/"))
#
# lgt_inpatient_data_import_list <- list(list(data_path = "../lgt-data/data-extract-201901/CLAHRCExtractToSend_QEH_20190107_IP.csv",
#                                             config_path = "lgt-config/inpatient/"),
#                                        list(data_path = "../lgt-data/data-extract-201901/CLAHRCExtractToSend_UHL_20190104_IP.csv",config_path = "lgt-config/inpatient/"))

