
#' recode_factors
#'
#' @param provided_data a tibble containing the imported dataset included all standard columns parsed
#' as the correct type
#' @param config_path path to the directory containing the config files for this dataset
#'
#' @return copy of provided_data with factor variables recoded to standard levels as
#' per the config files
#' @export
#'
#' @examples
recode_factors <- function(provided_data, config_path) {
  # TO BE IMPLEMENTED!

}

#' get_import_col_types
#'
#' @param config_path path to the config files for a given dataset
#'
#' @return a column specification to be used for parsing the dataset, as a named vector of
#' expressions. The expressions are readr collectors, and the names specify the columns they
#' will parse.
#' @export
#'
#' @examples
get_import_col_types <- function(config_path) {

  # Temporary hard-coded example
  # NEEDS REWRITING TO CREATE OUTPUT FROM CONFIG FILES

  provided_gender_levels <- rlang::expr(c("F", "M","N", "U", "Not Known", "Not Specified"))

  colImportTypes <- rlang::exprs(
    readr::col_character(),
    readr::col_factor(levels = !!provided_gender_levels),
    readr::col_character()
    )

  colImportNames <- c(
    "PAT_CODE",
    "SEX",
    "agegroup"
  )

  colImportTypes <- rlang::set_names(colImportTypes, colImportNames)

  colImportTypes
}

#' get_colname_mapping
#'
#' @param config_path path to the config files for a given dataset
#'
#' @return character vector specifying column renaming, of the form
#' c(new_name_1 = "old_name_1", new_name_2 = "old_name_2")
#' @export
#'
#' @examples
get_colname_mapping <- function(config_path) {
  # Temporary hard-coded example
  # NEEDS REWRITING TO CREATE OUTPUT FROM CONFIG FILES
  col_mapping_tbl <- lgt_col_mapping()
}

#' import_and_standardise
#'
#' @param data_import_list list of named lists, each named list has two elements called
#' data_path and config_path, whose values are character strings specifying the paths
#' to i) a csv file to import data from and ii) a folder containing hospitalflow config
#' files.
#'
#' @return list of tibbles, each containing standardised import of one data file from data_paths
#' @export
#'
#' @examples
import_and_standardise <- function(data_import_list) {

  # Take the data_import_list and for each element x, load the data located at data_path
  # using configuration specified by the files at config_path.
  # In particular, use the column specification generated by
  # get_import_col_types from the config files.
  data_config_list <- lapply(data_import_list,
                             function(x) {list(data = readr::read_csv(x$data_path,
                                                                      locale = readr::locale(tz = 'Europe/London'),
                                                                      col_types = eval(rlang::call2(readr::cols,
                                                                                                    !!!get_import_col_types(x$config_path),
                                                                                                    .default = readr::col_skip()))),
                                               config_path = x$config_path)
    })

  # Rename the columns in each imported dataset, using the name mapping onto standard hospitalflow
  # variable names specified in the config files at the specified config_path.
  data_config_list <- lapply(data_config_list,
                             function(x) {
                               list(data = standardise_column_names(x$data,
                                                                    get_colname_mapping(x$config_path) %>%
                                                                      dplyr::filter(provided %in% colnames(x$data))
                                                                    ),
                                    config_path = x$config_path)
                               })

  # HERE NEED TO DEAL WITH FORMAT CONVERSIONS: DATETIMES, FACTORS, ETC.

  # Extract the data as a tibble for each imported file, and return as a list of these tibbles.
  lapply(data_config_list, function(x) x$data)
}
